### ISSUE TITLE
How to use `ns.fnl` for Nvim config?

### ISSUE THREAD

**Issue by bangedorrunt** [mrichards42/bulb#1]
Hi, thanks for making great lib for `fennel`. I'm wondering how could I use `ns` to structure my Neovim config. I wish there could be an document for integration with Nvim.

**Comment by mrichards42** [comment]
Hi @babygau glad you've found this project useful! Before I get into too much detail, just a caveat that this is very much alpha quality, and I'm likely to revisit some decisions before I give it an initial release.

## NS macros

One of the big things I might revisit is that `ns` macro module. The general consensus among Fennel maintainers (based on discussion in the #fennel irc/matrix [channel](https://github.com/bakpakin/Fennel#resources)) is that best practice is to follow the standard lua module conventions and avoid macros like `ns` and `defn` that hide the module system. The preferred solution is just to define normal functions, and then return a table of them at the end of the file. You can see that style in the Fennel source itself (e.g. here are builtin [specials](https://github.com/bakpakin/Fennel/blob/db601b7426f85d5965a9a4fbfd9c153256a2eadc/src/fennel/specials.fnl#L1300-L1308) and builtin [macros](https://github.com/bakpakin/Fennel/blob/db601b7426f85d5965a9a4fbfd9c153256a2eadc/src/fennel/macros.fnl#L501-L519)).

To spell that out more clearly, there are basically two common ways of structuring lua modules:

1. Define local functions, return a table with those functions

```clj
(fn a [])         ; local functions
(fn b [])

{: a              ; return a table of functions
 : b}
```

2. Define a local table, add functions to the table as you go

```clj
(local M {})       ; module table

(fn M.a [])        ; functions defined directly into that table
(fn M.b [])

M                  ; return the table
```

All that said, the `ns` macros _can_ be used, but essentially it uses the second style. I'm not sure this is actually better, which is why I might just remove it

```clj
(require-macros :ns) ; import these macros into the current module
(ns my-module)       ; create a table for this module

(defn a [])          ; define functions, which are 'magically' added
(defn b [])          ; to the my-module table

(ns-export)          ; return the table
```

## Integration with neovim

I use neovim, but I actually haven't gotten around to rewriting any of my config in lua, much less fennel at this point. Assuming you're already using fennel for your config you should be able to drop in bulb as another dependency and it will just work. If you're looking for more details about how to get fennel running in neovim, I know https://github.com/Olical/aniseed is pretty popular, if a bit heavy, and https://github.com/rktjmp/hotpot.nvim looks pretty promising and minimal to me.

**Comment by bangedorrunt** [comment]
Thank you so much for your explanation. It's all good now. I'm looking forward to your new upgraded versions. Thanks to it, learning lisp/clj is so much fun and enjoyable.
